### ISSUE TITLE
Prepare new release?

### ISSUE THREAD

**Issue by emiliom** [ioos/pyoos#51]
Last release pushed to pypi was 0.6.2, from 2014 Aug. Some stuff have been added/fixed since then (master is labelled as 0.6.3-dev). Would be good to push a new release in the near future, specially after we resolve and merge  https://github.com/ioos/pyoos/pull/48

Looping in @ocefpaf b/c we've been talking a lot about pyoos recently, including a question about the ioos conda package.

**Comment by ocefpaf** [comment]
:+1: to a new release.

**Comment by emiliom** [comment]
With pull #53 now merged, let's try to issue a new release (0.6.3?) soon; maybe next week? @ocefpaf can then create an [updated conda package from that release; looks like he's almost all set.](https://github.com/ioos/conda-recipes/issues/685)

Hopefully after that, say in the second half of this month, we can discuss the longer-term maintenance of `pyoos` that @kwilcox [brought up recently](https://github.com/ioos/conda-recipes/issues/685#issuecomment-167255891), bringing in other relevant parties: @daf, @lukecampbell, and the big kahuna himself (@dpsnowden).

**Comment by ocefpaf** [comment]
I would like to solve #52 before creating the new release.  (But that should not hold the release.)
We could also try to improve the `docstrings` a little bit :grimacing:

**Comment by emiliom** [comment]
> I would like to solve #52 before creating the new release. (But that should not hold the release.)

#52 seems ambitious!

> We could also try to improve the docstrings a little bit

How about viewing a next release (0.6.3) as a mostly incremental wrap up of enhancements and clean-ups from the last 16 months? Then a follow-up release(s) can take all the time that's needed to  address #52 (py3x) and [documentation (docstrings, etc)](https://github.com/ioos/pyoos/issues/47)?

My 2 cents, anyway.

**Comment by ocefpaf** [comment]
> How about viewing a next release (0.6.3) as a mostly incremental wrap up of enhancements and clean-ups from the last 16 months? 

:+1:

**Comment by ocefpaf** [comment]
@kwilcox and @daf is it OK if I tag a `v0.6.3` against master?

**Comment by lukecampbell** [comment]
Yeah go ahead.

**Comment by daf** [comment]
:arrow_up:

**Comment by emiliom** [comment]
Thanks, @lukecampbell and @daf.

I went over the commit history since the last release (Aug 2014) and drafted a summary for this release. Please look it over and make changes as you see fit. Once the text is finalized, @ocefpaf will copy and paste to create the new release.

BTW, I think there are enough changes here that we should consider a version number > than the strictly incremental 0.6.3? eg, 0.7.0? But either way is fine with me.

Finally, @ocefpaf, I'm assuming the new draft-stage notebooks directory won't be included in the release? But I guess it doesn't matter since it's not code per se.

# Pyoos 0.6.3

Version 0.6.3 is a prerelease version of Pyoos containing improved features, bug fixes and code clean ups.

## Features
- Conda package now available at anaconda ioos channel (@ocefpaf)
- Added a named project-level logger (@kwilcox)
- Added flatten_element utilities convenience function to return record-style time series representation by variable standard name (@emiliom)
- Improvements to collectors and parsers:
	- CO-OPS (added SML 1.0.1 Network Identifier XPath) (@lukecampbell)
	- IoosSweSos (improved robustness of variable/attribute detection and code clean-up in describe sensor metadata; TimeSeries bug fix) (@lukecampbell, @kwilcox)
	- HADS (improved parser handling of datetimes, values, and NaN flags; improved collector datetime filter) (@emiliom, @daf, @kwilcox)
	- NERRS (added optional, alternate mechanism for service access based on a NERRS-CDMO issued token; improved latitude & longitude parsing; added missing and corrected misspelled variable names and units) (@emiliom, @ocefpaf)

## Fixes
- TravisCI testing fixed for conda package (@daf, @ocefpaf)
- Fixed several tests (@kwilcox, @daf, @ocefpaf)
- Whitespace / PEP8 code cleanup (@kwilcox)

**Comment by ocefpaf** [comment]
> BTW, I think there are enough changes here that we should consider a version number > than the strictly incremental 0.6.3? eg, 0.7.0? But either way is fine with me.

`v0.7.0` it is.  Makes more sense since minor version number usually means bugfix.  We do have some new features there.

> Finally, @ocefpaf, I'm assuming the new draft-stage notebooks directory won't be included in the release? But I guess it doesn't matter since it's not code per se.

Nope.  And I don't think we should create a source dist with that directory.  Specially if we manage to create/advertise some docs and examples based on the notebooks there.  People are more likely to "google" pyoos and find them here rather than looking into the source dist and finding them locally.

**Comment by ocefpaf** [comment]
@kwilcox Can you give me rights to update the source dist at PyPI?

**Comment by emiliom** [comment]
> v0.7.0 it is. Makes more sense since minor version number usually means bugfix. We do have some new features there.

:+1: 

> People are more likely to "google" pyoos and find [the notebooks] here rather than looking into the source dist and finding them locally.

Yup.

**Comment by daf** [comment]
@ocefpaf just gave you Maintainer rights, assuming your username is the same as on github.  If not, let me know what it is.

**Comment by ocefpaf** [comment]
Thanks @daf.  (My username if the same everywhere because it is never taken.  One of the few advantages of having a weird and non-nonsensical username :wink: )

**Comment by ocefpaf** [comment]
If someone wants to edit the release text go to https://github.com/ioos/pyoos/releases/tag/v0.7.0

Thanks @emiliom and @daf for making this happen!

**Comment by emiliom** [comment]
Awesome!! And all the way to PyPI! Thanks, @ocefpaf and @daf.

I'll be on the lookout for an [updated conda package.](https://github.com/ioos/conda-recipes/issues/685)

**Comment by ocefpaf** [comment]
See https://github.com/ioos/conda-recipes/pull/687
