### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ocefpaf** [ioos/pyoos#61]
I tested https://github.com/ioos/pyoos/pull/52 in production with both Python 2 and 3. Is it OK to issue a new release? I can take on the task myself if the authors agree is OK to do so.

**Comment by lukecampbell** [comment]
👍

**Comment by ocefpaf** [comment]
Thanks @lukecampbell and @daf!

Done: https://github.com/ioos/pyoos/releases/tag/v0.8.0

Preparing a conda-forge update now. Not sure who has the credentials to update PyPI.

**Comment by daf** [comment]
@ocefpaf @lukecampbell I just updated PyPI.  Been a while, hopefully it went clean.

**Comment by ocefpaf** [comment]
Just tried a quick install from PyPI locally and it worked. Thanks @daf!

**Comment by lukecampbell** [comment]
👍
