### ISSUE TITLE
AwcRest stations_url failure

### ISSUE THREAD

**Issue by ocefpaf** [ioos/pyoos#63]
`AwcRest` uses http://weather.noaa.gov/data/nsd_cccc.txt for the `stations_url` but that URL is no longer available. I do not use AwcRest so I am not sure if the service is still available or just that URL changed.

Any user out there care to comment? Should we remove `awc` from `pyoos`?

Here is the message:
```
This Service is no longer available

In Accordance with NWS Service Change Notice 16-16 this service has been discontinued.
Please see Weather.gov and tgftp.nws.noaa.gov (raw data)
```

**Comment by lukecampbell** [comment]
Awc was replaced with ADDS.

**Comment by lukecampbell** [comment]
https://www.aviationweather.gov/docs/metar/stations.txt

https://www.aviationweather.gov/dataserver/example?datatype=metar

**Comment by ocefpaf** [comment]
I don't understand `Awc`, b/c I never used it, but https://www.aviationweather.gov/docs/metar/stations.txt does not seem to be a "drop-in" replacement for https://www.aviationweather.gov/docs/metar/stations.txt I am correct? I cannot reverse engineer https://www.aviationweather.gov/docs/metar/stations.txt as it is no longer available :unamused: 

So it would be best if the original author of `AwcRest`, or any active users of that service, to tackle this task.

**Comment by lukecampbell** [comment]
In the mean time we should probably remove the AWC Modules, as they are no longer supported.

**Comment by ocefpaf** [comment]
> In the mean time we should probably remove the AWC Modules, as they are no longer supported.

That is what I was finishing above :smile: 
I was just waiting for some AWC user to chime in though. Anyways, I will not remove the code but I will add a "not implemented" in my next PR.
