### ISSUE TITLE
HADS collector parse data issue

### ISSUE THREAD

**Issue by DanRamage** [ioos/pyoos#67]
In the _parse_data function on line 122: "value = float(fields[4]) if fields[4] != 'NaN' else npNan" if fields[4] is an empty string, a Value Error exception is thrown during the float() call. 
I'm not sure how that should be handled, whether a blank value placeholder to keep the time series consistent or if that record should not be appended at all.

**Comment by lukecampbell** [comment]
https://github.com/ioos/pyoos/blob/ef14b3eb882ba490be6d4233fd49e3b73958425d/pyoos/parsers/hads.py#L121

For others viewing the issue.
