### ISSUE TITLE
Issue new minor release (0.8.4?), with hads fixes since December

### ISSUE THREAD

**Issue by emiliom** [ioos/pyoos#79]
The HADS collector is completely dysfunctional in the last official pyoos release (0.8.3) issued Dec. 13. The two breaking problems have now been fixed in master (PR's #75, "update hads URLS", and #78, "hads collector update to support unverified SSL certs"). See also discussions in #77

Issuing a minor release and propagating it to conda-forge (via @ocefpaf) will make these important fixes widely available.

**Comment by ocefpaf** [comment]
> Issuing a minor release and propagating it to conda-forge (via @ocefpaf) will make these important fixes widely available.

Makes sense. I am on it...

**Comment by ocefpaf** [comment]
Done in https://github.com/conda-forge/pyoos-feedstock/pull/7

@daf can you upload the new release to PyPI?

**Comment by emiliom** [comment]
Wow, that was fast!! Thank you!

**Comment by daf** [comment]
Uploaded to pypi!

**Comment by ocefpaf** [comment]
Thanks @daf!
